// src/config/defaultData/cards.js

export const CARDS_BY_CATEGORY = {
  // Потребности (глаголы)
  needs: [
    { text: 'Пить', emoji: '🚰', wordType: 'verb' },
    { text: 'Есть', emoji: '🍽️', wordType: 'verb' },
    { text: 'Спать', emoji: '😴', wordType: 'verb' },
    { text: 'Гулять', emoji: '🚶', wordType: 'verb' },
    { text: 'Играть', emoji: '🎮', wordType: 'verb' },
    { text: 'Туалет', emoji: '🚽', wordType: 'verb' },
    { text: 'Помощь', emoji: '🆘', wordType: 'verb' },
    { text: 'Отдыхать', emoji: '🛋️', wordType: 'verb' },
    { text: 'Кушать', emoji: '🍜', wordType: 'verb' },
    { text: 'Мыться', emoji: '🛁', wordType: 'verb' },
  ],
  // Чувства (существительные)
  feelings: [
    { text: 'Радость', emoji: '😊', wordType: 'noun' },
    { text: 'Грусть', emoji: '😢', wordType: 'noun' },
    { text: 'Злость', emoji: '😡', wordType: 'noun' },
    { text: 'Страх', emoji: '😨', wordType: 'noun' },
    { text: 'Усталость', emoji: '😩', wordType: 'noun' },
    { text: 'Больно', emoji: '🤕', wordType: 'noun' },
    { text: 'Спокойствие', emoji: '😌', wordType: 'noun' },
    { text: 'Весело', emoji: '😄', wordType: 'noun' },
    { text: 'Скучно', emoji: '😑', wordType: 'noun' },
    { text: 'Интересно', emoji: '🤔', wordType: 'noun' },
  ],
  // Действия (глаголы)
  actions: [
    { text: 'Идти', emoji: '🚶', wordType: 'verb' },
    { text: 'Сидеть', emoji: '🪑', wordType: 'verb' },
    { text: 'Стоять', emoji: '🧍', wordType: 'verb' },
    { text: 'Бежать', emoji: '🏃', wordType: 'verb' },
    { text: 'Прыгать', emoji: '🤸', wordType: 'verb' },
    { text: 'Рисовать', emoji: '🎨', wordType: 'verb' },
    { text: 'Смотреть', emoji: '👀', wordType: 'verb' },
    { text: 'Слушать', emoji: '👂', wordType: 'verb' },
    { text: 'Танцевать', emoji: '💃', wordType: 'verb' },
    { text: 'Петь', emoji: '🎤', wordType: 'verb' },
  ],
  // Еда (существительные)
  food: [
    { text: 'Вода', emoji: '💧', wordType: 'noun' },
    { text: 'Молоко', emoji: '🥛', wordType: 'noun' },
    { text: 'Хлеб', emoji: '🍞', wordType: 'noun' },
    { text: 'Яблоко', emoji: '🍎', wordType: 'noun' },
    { text: 'Суп', emoji: '🍲', wordType: 'noun' },
    { text: 'Каша', emoji: '🥣', wordType: 'noun' },
    { text: 'Печенье', emoji: '🍪', wordType: 'noun' },
    { text: 'Сок', emoji: '🧃', wordType: 'noun' },
    { text: 'Банан', emoji: '🍌', wordType: 'noun' },
    { text: 'Огурец', emoji: '🥒', wordType: 'noun' },
  ],
  // Игрушки (существительные)
  play: [
    { text: 'Мяч', emoji: '⚽', wordType: 'noun' },
    { text: 'Книжка', emoji: '📖', wordType: 'noun' },
    { text: 'Машинка', emoji: '🚗', wordType: 'noun' },
    { text: 'Музыка', emoji: '🎵', wordType: 'noun' },
    { text: 'Пазлы', emoji: '🧩', wordType: 'noun' },
    { text: 'Мягкая игрушка', emoji: '🧸', wordType: 'noun' },
    { text: 'Конструктор', emoji: '🔧', wordType: 'noun' },
    { text: 'Рисование', emoji: '🎨', wordType: 'noun' },
    { text: 'Кубики', emoji: '🧱', wordType: 'noun' },
    { text: 'Качели', emoji: '🪢', wordType: 'noun' },
  ],
  // Одежда (существительные)
  clothes: [
    { text: 'Кепка', emoji: '🧢', wordType: 'noun' },
    { text: 'Куртка', emoji: '🧥', wordType: 'noun' },
    { text: 'Штаны', emoji: '👖', wordType: 'noun' },
    { text: 'Футболка', emoji: '👕', wordType: 'noun' },
    { text: 'Носки', emoji: '🧦', wordType: 'noun' },
    { text: 'Обувь', emoji: '👟', wordType: 'noun' },
    { text: 'Шарф', emoji: '🧣', wordType: 'noun' },
    { text: 'Варежки', emoji: '🧤', wordType: 'noun' },
  ],
  // Транспорт (существительные)
  transport: [
    { text: 'Машина', emoji: '🚗', wordType: 'noun' },
    { text: 'Автобус', emoji: '🚌', wordType: 'noun' },
    { text: 'Поезд', emoji: '🚆', wordType: 'noun' },
    { text: 'Самолёт', emoji: '✈️', wordType: 'noun' },
    { text: 'Корабль', emoji: '🚢', wordType: 'noun' },
    { text: 'Велосипед', emoji: '🚲', wordType: 'noun' },
    { text: 'Мотоцикл', emoji: '🏍️', wordType: 'noun' },
  ],
  // Животные (существительные, одушевлённые)
  animals: [
    { text: 'Кошка', emoji: '🐱', wordType: 'noun', animate: true },
    { text: 'Собака', emoji: '🐶', wordType: 'noun', animate: true },
    { text: 'Кролик', emoji: '🐰', wordType: 'noun', animate: true },
    { text: 'Попугай', emoji: '🦜', wordType: 'noun', animate: true },
    { text: 'Рыбка', emoji: '🐟', wordType: 'noun', animate: true },
    { text: 'Хомяк', emoji: '🐹', wordType: 'noun', animate: true },
    { text: 'Корова', emoji: '🐄', wordType: 'noun', animate: true },
    { text: 'Лошадь', emoji: '🐴', wordType: 'noun', animate: true },
    { text: 'Свинья', emoji: '🐷', wordType: 'noun', animate: true },
    { text: 'Обезьяна', emoji: '🐒', wordType: 'noun', animate: true },
  ],
  // Цвета (прилагательные)
  colors: [
    { text: 'Красный', emoji: '🔴', wordType: 'adjective' },
    { text: 'Синий', emoji: '🔵', wordType: 'adjective' },
    { text: 'Жёлтый', emoji: '🟡', wordType: 'adjective' },
    { text: 'Зелёный', emoji: '🟢', wordType: 'adjective' },
    { text: 'Оранжевый', emoji: '🟠', wordType: 'adjective' },
    { text: 'Фиолетовый', emoji: '🟣', wordType: 'adjective' },
    { text: 'Розовый', emoji: '🩷', wordType: 'adjective' },
    { text: 'Белый', emoji: '⚪', wordType: 'adjective' },
    { text: 'Чёрный', emoji: '⚫', wordType: 'adjective' },
    { text: 'Коричневый', emoji: '🟤', wordType: 'adjective' },
  ],
  // Формы (существительные)
  shapes: [
    { text: 'Круг', emoji: '⭕', wordType: 'noun' },
    { text: 'Квадрат', emoji: '🟨', wordType: 'noun' },
    { text: 'Треугольник', emoji: '🔺', wordType: 'noun' },
    { text: 'Прямоугольник', emoji: '▬', wordType: 'noun' },
    { text: 'Овал', emoji: '⚪', wordType: 'noun' },
    { text: 'Звезда', emoji: '⭐', wordType: 'noun' },
    { text: 'Сердечко', emoji: '❤️', wordType: 'noun' },
  ],
  // Числа (будут обрабатываться как числительные)
  numbers: [
    { text: '1', emoji: '1️⃣', wordType: 'other' },
    { text: '2', emoji: '2️⃣', wordType: 'other' },
    { text: '3', emoji: '3️⃣', wordType: 'other' },
    { text: '4', emoji: '4️⃣', wordType: 'other' },
    { text: '5', emoji: '5️⃣', wordType: 'other' },
    { text: '6', emoji: '6️⃣', wordType: 'other' },
    { text: '7', emoji: '7️⃣', wordType: 'other' },
    { text: '8', emoji: '8️⃣', wordType: 'other' },
    { text: '9', emoji: '9️⃣', wordType: 'other' },
    { text: '10', emoji: '🔟', wordType: 'other' },
  ],
  // Семья (одушевлённые существительные)
  family: [
    { text: 'Мама', emoji: '👩', wordType: 'noun', animate: true },
    { text: 'Папа', emoji: '👨', wordType: 'noun', animate: true },
    { text: 'Бабушка', emoji: '👵', wordType: 'noun', animate: true },
    { text: 'Дедушка', emoji: '👴', wordType: 'noun', animate: true },
    { text: 'Сестра', emoji: '👧', wordType: 'noun', animate: true },
    { text: 'Брат', emoji: '👦', wordType: 'noun', animate: true },
    { text: 'Тётя', emoji: '👩', wordType: 'noun', animate: true },
    { text: 'Дядя', emoji: '👨', wordType: 'noun', animate: true },
  ],
  // Места (неодушевлённые существительные)
  places: [
    { text: 'Дом', emoji: '🏠', wordType: 'noun' },
    { text: 'Садик', emoji: '🏫', wordType: 'noun' },
    { text: 'Школа', emoji: '📚', wordType: 'noun' },
    { text: 'Магазин', emoji: '🛒', wordType: 'noun' },
    { text: 'Парк', emoji: '🌳', wordType: 'noun' },
    { text: 'Больница', emoji: '🏥', wordType: 'noun' },
    { text: 'Площадка', emoji: '🎠', wordType: 'noun' },
    { text: 'Гости', emoji: '🏡', wordType: 'noun' },
  ],
};